image:
  file: .gitpod.Containerfile
tasks:
  - init: |
      direnv allow
      mkdir -p /home/gitpod/.config/nix &&
      echo 'sandbox = false' >> /home/gitpod/.config/nix/nix.conf

vscode:
  extensions:
    - bbenoist.Nix
    - usernamehw.errorlens